### ISSUE TITLE
Push notifications occur at the wrong time

### ISSUE THREAD

**Issue by djeedai** [vrickey123/LeapForWaniKani#23]
Hi,

I am receiving random push notifications saying there are some reviews or lessons, but there's nothing. The timing is completely off. Is this a timezone issue? Conversely when I actually have something to do I don't get any notification. I installed this app mainly for push notifications, if those don't work then unfortunately I don't see much value anymore in it compared to using the website directly. 😢

**Comment by vrickey123** [comment]
@djeedai Hey, thanks for the bug report! Yes, I agree with you-- there is a bug in the push notifications that causes them to send even though you may not have lessons and reviews in your queue. I've seen it.

Right now, there is a hard-coded background request that checks each user's lessons and reviews status every hour.

The way it _should work_ is if you have lessons and reviews, which is indicated by a non-empty `List<Int>` of `summary.data.lessons` and `summary.data.reviews`, then a push notification will fire and open the `MainActivity` AKA the Dashboard.

For some reason, I think we're getting a response from the API that the `List<int>` is non-empty, we fire the push, but there actually aren't any lessons or reviews.

I don't think it is a timezone issue. If anything, I would start with investigating the values that are returned in the `summary.data.lessons` and `summary.data.reviews` to make sure content is actually there and we're working with the data that we expect.

[SummaryNotificationWorker](https://github.com/vrickey123/LeapForWaniKani/blob/develop/app/src/main/java/com/leapsoftware/leapforwanikani/workers/SummaryNotifyWorker.kt#L57-L62)
The hourly background job that fires a push notification.

[MainActivity#getActivityRequestCode](https://github.com/vrickey123/LeapForWaniKani/blob/develop/app/src/main/java/com/leapsoftware/leapforwanikani/MainActivity.kt#L48-L49)
The logic that determines what kind of notification to send to open the `MainActivity` (Dashboard). This is where I would start.

[LeapNotificationManager](https://github.com/vrickey123/LeapForWaniKani/blob/develop/app/src/main/java/com/leapsoftware/leapforwanikani/utils/LeapNotificationManager.kt#L57-L62)
Builds a push notification with messages and on-click actions.

The long term goal of this app was to provide an open source option for other Android developers who use WaniKani to help create new features like a Lessons and Reviews screen, but I'm afraid it didn't catch on. Right now we're still at v1.0.0; a simple Dashboard and web wrapper. 

I'll try to take a look, but this is project is on a hiatus for now. If you're feeling adventurous, you can try to make a fix and test it out on your device, then open a PR here.

**Comment by vrickey123** [comment]
@djeedai Ah, you know what, I think I found it. The [WaniKani Summary API](https://docs.api.wanikani.com/20170710/#summary), the data object that backs our Push Notifications, returns an `available_at` field.

Currently, the app just does a naive check to see if the `subject_ids` (the upcoming Radicals, Kanji, and Vocab) are not empty instead of checking the `available_at` time.

So you were on the right track with a timestamp-related bug.

I think the solution we want is to check if the `availableAt` Date is before or equal to now. Something like:

```
Date availableAt = summary.data.availableAt
if (LocalDate.isBefore(availableAt) || LocalDate.isEqual(availableAt) {
   ... // send push notification
}
```

Let me try it out and I'll report back.

**Comment by vrickey123** [comment]
@djeedai I opened a PR and installed a build on my phone. I'll see how it goes.

**Comment by vrickey123** [comment]
@djeedai I just rolled out a release for notification bug fixes and Notification Preferences accessible from the Nav Drawer that allow you to set your notification frequency to once every 1-24 hours. The Google Play app review times are about a week now, I guess because many of Google's offices have closed. Keep an eye out for the release. Thanks for making the report.
